server {
    listen 127.0.0.1:8091;
    server_name 0xm4r71n.com www.0xm4r71n.com;

    root /var/www/0xm4r71n/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /var/log/nginx/0xm4r71n-access.log;
    error_log /var/log/nginx/0xm4r71n-error.log;
}
